class DishDetails {
  final List<String> ingredients;
  final List<String> method;

  const DishDetails({
    required this.ingredients,
    required this.method,
  });
}

final aglioOlioDetails = DishDetails(
  ingredients: [
    '300g spaghetti',
    '4 cloves of garlic',
    '2 red pepperoni',
    '1 bunch of flat-leaf parsley',
    '60 ml olive oil or neutral vegetable oil',
    'Sea salt and pepper',
    'Optional: grated Parmesan cheese',
  ],
  method: [
    'Wash the parsley, shake dry, pluck off the leaves and chop.',
    'Cut the chili peppers lengthwise, remove the seeds, wash and cut into thin strips or rings.',
    'Peel the garlic and slice thinly.',
    'Cook the spaghetti in plenty of boiling salted water for about 10 minutes until al dente.',
    'Drain and set aside.',
    'Heat oil in a pan and sauté the garlic, parsley, and chili pepper over medium heat for 2-3 minutes.',
    'Be careful that the garlic doesn\'t turn brown, otherwise it will become bitter.',
    'Add the spaghetti to the pan and toss to coat.',
    'Season with salt and pepper.',
    'Serve the spaghetti on preheated plates.',
  ],
);

final tomatoDetails = DishDetails(
  ingredients: [
    'Water for boiling',
    'Salt',
    'Spaghetti',
    '4-6 tomatoes',
    '1 tbsp oil',
    '1 tbsp finely chopped garlic',
    '2 tsp red chili flakes',
    '1 finely chopped onion',
    'Finely chopped capsicum',
    'Finely chopped carrot',
    '1/2 tsp salt',
    '1 tsp red chili powder',
    '1/2 tsp black pepper powder',
    '1 tsp mixed herbs seasoning',
    'Basil leaves',
    'Sugar',
    'Tomato ketchup (optional)',
    'Fresh cream/fresh cheese',
  ],
  method: [
    'Boil water with salt in a large pot.',
    'Add spaghetti and cook until al dente, then drain.',
    'Heat oil in a pan over medium heat.',
    'Add garlic and sauté for 1 minute until fragrant.',
    'Add chopped onion and cook for 2-3 minutes until translucent.',
    'Add chopped capsicum and carrot, cook for 2-3 minutes.',
    'Add tomatoes and cook until softened (about 5 minutes).',
    'Add red chili flakes, chili powder, salt, pepper, and mixed herbs.',
    'Add basil leaves and a pinch of sugar for balance.',
    'Simmer the sauce for 5-10 minutes.',
    'Add tomato ketchup if desired for extra flavor.',
    'Combine cooked spaghetti with the sauce.',
    'Stir in fresh cream or cheese for richness.',
    'Serve hot and enjoy!',
  ],
);

final creamyGarlicDetails = DishDetails(
  ingredients: [
    '2 teaspoons olive oil',
    '4 garlic cloves, minced',
    '2 tablespoons butter',
    '3 cups chicken broth (or more as needed)',
    '1/2 teaspoon ground black pepper',
    '1/4 teaspoon salt',
    '1/2 pound spaghetti',
    '1 cup grated Parmesan cheese',
    '3/4 cup heavy cream',
    '1 1/2 tablespoons dried parsley',
  ],
  method: [
    'Gather all ingredients.',
    'Heat olive oil in a medium pan over medium heat.',
    'Add minced garlic and stir until fragrant (1-2 minutes).',
    'Add butter and stir constantly until melted.',
    'Pour in 3 cups chicken broth; add pepper and salt.',
    'Bring to a boil.',
    'Add spaghetti and cook, stirring occasionally, until tender yet firm (about 12 minutes).',
    'Add more chicken broth if pasta starts to stick to the pan.',
    'Add Parmesan cheese, heavy cream, and dried parsley.',
    'Mix until thoroughly combined.',
    'Serve immediately while hot.',
  ],
);

final spicyDetails = DishDetails(
  ingredients: [
    'For Pasta:',
    '  • 1 tbsp salt',
    '  • 2 cups penne pasta (or spaghetti)',
    'For Sauce:',
    '  • 4 tbsp olive oil',
    '  • 2 tbsp butter',
    '  • 4 cloves garlic (minced)',
    '  • 1 tsp chili flakes',
    '  • 1 small onion (finely chopped)',
    '  • 1/2 cup tomato paste',
    '  • 1 cup heavy cream',
    '  • 1/4 tsp salt',
    '  • 1 tsp mixed herb',
    '  • 1/2 tsp black pepper',
    '  • 1/2 cup Parmesan cheese',
    'For Garnishing:',
    '  • Chili flakes',
    '  • Chopped coriander',
  ],
  method: [
    'Place a large pot on the stove and fill with water.',
    'Bring water to a rolling boil.',
    'Add 1 tbsp of salt to the water and 2 cups of pasta to the pot.',
    'Boil the pasta for about 8-10 minutes or according to package instructions.',
    'Stir occasionally.',
    'Reserve 1 cup of pasta water before draining.',
    'Drain the excess water and rinse under cold water to stop cooking.',
    'Set aside for later use.',
    'Bring a large pot and put it on the stove over medium heat.',
    'Pour 4 tbsp of olive oil into it.',
    'Add 2 tbsp of butter and let it melt.',
    'Add 4 cloves of minced garlic and 1 tsp of chili flakes.',
    'Cook for 1 minute while stirring frequently.',
    'Add 1 small finely chopped onion and cook for 2-3 minutes.',
    'Add 1/2 cup of tomato paste and cook for an additional 2-3 minutes.',
    'Pour in 1 cup of heavy cream and mix thoroughly.',
    'Sprinkle salt, mixed herb, and black pepper. Keep stirring.',
    'Add a little pasta water and let it simmer.',
    'Sprinkle 1/2 cup of grated parmesan cheese until fully melted.',
    'If sauce is too thick, add more reserved pasta water.',
    'Add cooked pasta to the sauce and toss gently.',
    'Garnish with chili flakes and chopped coriander.',
    'Serve on a plate with grated parmesan cheese on top.',
  ],
);
