// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGLLqkplW6FjSylfxFT4iC3RcYGWOK_lo',
    appId: '1:75890959312:web:99ad4752d128b3f9ffcfd5',
    messagingSenderId: '75890959312',
    projectId: 'pasta-shop-5ca1c',
    authDomain: 'pasta-shop-5ca1c.firebaseapp.com',
    storageBucket: 'pasta-shop-5ca1c.firebasestorage.app',
    measurementId: 'G-6FF787GJZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54Fhuh3-4wYVfa1JiRazHwTPNl1dRKYs',
    appId: '1:75890959312:android:bee70948bcba065dffcfd5',
    messagingSenderId: '75890959312',
    projectId: 'pasta-shop-5ca1c',
    storageBucket: 'pasta-shop-5ca1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_8Aj2tcfpy1cxnkJVRoqs5PyGBk7p_9o',
    appId: '1:75890959312:ios:ba3c6c18372e7237ffcfd5',
    messagingSenderId: '75890959312',
    projectId: 'pasta-shop-5ca1c',
    storageBucket: 'pasta-shop-5ca1c.firebasestorage.app',
    iosClientId: '75890959312-t7afplcua5hkkrldghsdd7nt7ej0bi1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.layout2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_8Aj2tcfpy1cxnkJVRoqs5PyGBk7p_9o',
    appId: '1:75890959312:ios:ba3c6c18372e7237ffcfd5',
    messagingSenderId: '75890959312',
    projectId: 'pasta-shop-5ca1c',
    storageBucket: 'pasta-shop-5ca1c.firebasestorage.app',
    iosClientId: '75890959312-t7afplcua5hkkrldghsdd7nt7ej0bi1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.layout2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGLLqkplW6FjSylfxFT4iC3RcYGWOK_lo',
    appId: '1:75890959312:web:2a7bb5d5e840257dffcfd5',
    messagingSenderId: '75890959312',
    projectId: 'pasta-shop-5ca1c',
    authDomain: 'pasta-shop-5ca1c.firebaseapp.com',
    storageBucket: 'pasta-shop-5ca1c.firebasestorage.app',
    measurementId: 'G-12TLC9NVH0',
  );

}